# Generated by Django 3.2.6 on 2021-09-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210919_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avatarUrl',
            new_name='avatar_url',
        ),
    ]
